apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix-container
          image: netflix-app:latest       # 👈 EXACT NAME
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-service
spec:
  type: NodePort
  selector:
    app: netflix
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
